FROM rg34xx-sdl2-builder:latest

RUN dpkg --add-architecture armhf \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gcc-arm-linux-gnueabihf \
      g++-arm-linux-gnueabihf \
      ccache \
      libsdl2-dev:armhf \
 && rm -rf /var/lib/apt/lists/*

ENV CCACHE_DIR=/ccache \
    CCACHE_BASEDIR=/workspace \
    CCACHE_COMPILERCHECK=content

WORKDIR /workspace
